@host = http://localhost:5090

POST {{host}}/news-score
Content-Type: application/json
Accept: application/json

{
  "measurements": [
    { "type": "TEMP", "value": 37 },
    { "type": "HR", "value": 60 },
    { "type": "RR", "value": 5 }
  ]
}

###
